# Generated by Django 3.1.2 on 2021-11-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_lib', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'commune',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Garde',
            fields=[
                ('gar_id', models.AutoField(primary_key=True, serialize=False)),
                ('gar_dated', models.DateField(blank=True, db_column='gar_dateD', null=True)),
                ('gar_datef', models.DateField(blank=True, db_column='gar_dateF', null=True)),
            ],
            options={
                'db_table': 'garde',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('ph_id', models.AutoField(primary_key=True, serialize=False)),
                ('ph_lat', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('ph_lng', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('ph_adresse', models.CharField(blank=True, max_length=70, null=True)),
                ('ph_nom', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'pharmacie',
                'managed': False,
            },
        ),
    ]
