# Generated by Django 3.1.2 on 2021-11-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traiter',
            fields=[
                ('id_tr', models.AutoField(primary_key=True, serialize=False)),
                ('datecreate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'traiter',
                'managed': False,
            },
        ),
    ]
